#!/bin/bash

NGROK_DOMAIN=ngrok.xuqplus.space

rm -rf ngrok
git clone https://github.com/inconshreveable/ngrok.git

openssl genrsa -out rootCA.key 4096
openssl req -x509 -new -nodes -key rootCA.key -subj "/CN="$NGROK_DOMAIN -days 5000 -out rootCA.pem
openssl genrsa -out device.key 4096
openssl req -new -key device.key -subj "/CN="$NGROK_DOMAIN -out device.csr
openssl x509 -req -in device.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out device.crt -days 5000

cp rootCA.pem ngrok/assets/client/tls/ngrokroot.crt
cp device.crt ngrok/assets/server/tls/snakeoil.crt
cp device.key ngrok/assets/server/tls/snakeoil.key

mkdir conf-eg/certs/
rm -rf conf-eg/certs/*
cp rootCA.pem rootCA.key rootCA.srl device.crt device.key device.csr conf-eg/certs/
rm -rf rootCA.pem rootCA.key rootCA.srl device.crt device.key device.csr

cp src/in-docker-make ngrok/
docker run --rm -v $(pwd)/ngrok:/root/work/ xuqplus/cent6-ngrok-go:0.3 /root/work/in-docker-make
